// src/intf/net/tls.h
#ifndef NET_TLS_H
#define NET_TLS_H

#include <stdint.h>
#include <stdbool.h>
#include "net/tcp.h"

/*
 * ktls - minimal secure record layer over this kernel's tcp_conn_t,
 * built to give an "https://" URL something real to connect to.
 *
 * WHAT THIS IS: a record-framed, AES-256-GCM-encrypted channel with a
 * handshake shaped like a TLS ClientHello/ServerHello exchange.
 *
 * WHAT THIS IS NOT: RFC 5246/8446-compliant TLS. There is no X.509, no
 * certificate chain, no signature verification, and the initial key
 * material crosses the wire unauthenticated (an active
 * man-in-the-middle can substitute their own key during the
 * handshake). This is the exact same trust model Deliver's own
 * KEY:<base64> exchange already documents and accepts (see
 * dlr_proto.h) - "enough to get two ends to accept a connection and
 * transfer data" over an otherwise-passive LAN, not a defense against
 * an active attacker. Do not use this for anything that needs real
 * transport security; a proper TLS stack (certificate validation,
 * ECDHE, a real ClientHello/ServerHello with cipher negotiation) is
 * future work if that's ever needed.
 *
 * Wire format:
 *   Handshake (once, unencrypted):
 *     client -> server: "KTLS1\0" (6 bytes) + 32-byte client session key
 *     server -> client: 1-byte status (0x01 = accepted)
 *   Records (after handshake, either direction):
 *     4-byte BE length (of nonce+ciphertext+tag) |
 *     12-byte nonce | ciphertext | 16-byte tag
 *   The session key is generated by the client with random_bytes()
 *   and used directly as the AES-256-GCM key for both directions; a
 *   fresh random nonce is drawn per record, so key reuse across
 *   records is safe against nonce collision for any realistic session
 *   length.
 */

typedef struct {
    tcp_conn_t* conn;
    uint8_t     key[32];
    bool        established;
} ktls_conn_t;

// Client side: opens the TCP connection then performs the ktls
// handshake. Returns NULL on any failure (connect, handshake, OOM).
ktls_conn_t* ktls_connect(uint32_t ip, uint16_t port, uint32_t timeout_ms);

// Server side: given an already-accepted tcp_conn_t (e.g. from
// tcp_accept()), completes the server half of the handshake. Returns
// NULL on failure; does NOT close `conn` on failure - the caller owns
// that either way.
ktls_conn_t* ktls_server_handshake(tcp_conn_t* conn, uint32_t timeout_ms);

// Encrypts and sends `len` bytes as one record. Returns true only if
// the whole record was accepted by the underlying TCP send.
bool ktls_send(ktls_conn_t* k, const void* data, uint32_t len);

// Reads and decrypts the next complete record into `buf` (must be at
// least `cap` bytes). Returns the plaintext length, 0 if the peer
// closed, or -1 on a framing/decrypt error (the connection should be
// considered dead at that point - a failed GCM tag means the stream
// can no longer be trusted).
int32_t ktls_recv(ktls_conn_t* k, void* buf, uint32_t cap, uint32_t timeout_ms);

// Closes the underlying TCP connection and frees `k`.
void ktls_close(ktls_conn_t* k);

#endif // NET_TLS_H
