#include <stdbool.h>
#include "print.h"
#include "graphics.h"
#include "x86_64/commandhandler.h"
#include "x86_64/commandreg.h"
#include "string.h"
#include "minimafshandler.h"
#include "x86_64/minimafs.h"
#include "x86_64/allocator.h"
#include "serial.h"
#include "systeminfo.h"
#include "music.h"
#include "x86_64/exec_trace.h"
#include "x86_64/safeints.h"

// ===========================================
// FORMAT COMMAND
// ===========================================

void cmd_format_debug(int argc, const char** argv) {
    serial_write_str("\n=== FORMAT DEBUG ===\n");
    graphics_write_textr("Formatting drive...\n");
    
    minimafs_disk_device_t* device = getminimadrive();
    if (!device) {
        graphics_write_textr("ERROR: No device!\n");
        serial_write_str("ERROR: getminimadrive() returned NULL\n");
        return;
    }
    
    serial_write_str("Device OK\n");
    
    uint64_t size = 128ULL * 1024 * 1024;  // 128 MB
    
    serial_write_str("Calling minimafs_format...\n");
    if (!minimafs_format(device, size, 0, "maindisk")) {
        graphics_write_textr("ERROR: Formatting failed!\n");
        serial_write_str("ERROR: minimafs_format returned false\n");
        return;
    }
    
    graphics_write_textr("Format OK. Mounting...\n");
    serial_write_str("Format succeeded. Calling minimafs_mount...\n");
    
    int mount_result = minimafs_mount(device, 0);
    if (mount_result != 1) {
        graphics_write_textr("ERROR: Mount failed! Code=");
        char buf[16];
        snprintf(buf, sizeof(buf), "%d", mount_result);
        graphics_write_textr(buf);
        graphics_write_textr("\n");
        serial_write_str("ERROR: minimafs_mount returned ");
        serial_write_dec(mount_result);
        serial_write_str("\n");
        return;
    }
    
    graphics_write_textr("Mounted OK.\n");
    serial_write_str("Mount succeeded.\n");
    
    minimafs_drive_t* drive = get_drive(0);
    if (!drive || !drive->mounted) {
        serial_write_str("ERROR: Drive 0 not accessible\n");
        graphics_write_textr("ERROR: Drive not accessible!\n");
        return;
    }
    
    serial_write_str("Drive 0 is mounted. Root block=");
    serial_write_dec(drive->storage_desc.root_block);
    serial_write_str("\n");
    
    minimafs_refresh_storage_desc(drive);

    serial_write_str("Creating system files...\n");
    graphics_write_textr("Creating system.conf...\n");

    minimafs_mkdir("0:/");
    minimafs_create_file("0:/system.conf", "text", "conf");

    // Build system.conf content — SYSTEMVER is a string from systeminfo.h
    char date_str[32];
    minimafs_get_datetime(date_str, sizeof(date_str));

    char* conf_content = (char*)alloc(512);
    if (!conf_content) {
        serial_write_str("ERROR: OOM for conf_content\n");
        return;
    }

    char* p = conf_content;
    p += sprintf(p, "# MinimalOS System Configuration\n");
    p += sprintf(p, "# Auto-generated by format\n");
    p += sprintf(p, "#\n");
    p += sprintf(p, "version=%s\n",   SYSTEMVER);
    p += sprintf(p, "formatted=%s\n", date_str);
    p += sprintf(p, "hostname=MinimalOS\n");
    p += sprintf(p, "drive=0\n");
    p += sprintf(p, "fs=MinimaFS\n");

    uint32_t conf_len = (uint32_t)(p - conf_content);

    // Open the file and write the content
    minimafs_file_handle_t* conf_file = minimafs_open("0:/system.conf", false);
    if (!conf_file) {
        serial_write_str("ERROR: Could not open system.conf for writing\n");
    } else {
        minimafs_write(conf_file, conf_content, conf_len);
        minimafs_close(conf_file);
        serial_write_str("system.conf written (");
        serial_write_dec(conf_len);
        serial_write_str(" bytes)\n");
    }

    free_mem(conf_content);
    graphics_write_textr("File created OK.\n");

    // Verify the file was registered in the root folder
    minimafs_folder_desc_t* root_desc = (minimafs_folder_desc_t*)alloc(sizeof(minimafs_folder_desc_t));
    if (!root_desc) {
        serial_write_str("ERROR: OOM for root_desc\n");
        return;
    }

    if (!minimafs_read_folder_desc(drive, "/", root_desc)) {
        serial_write_str("ERROR: Failed to read root folder.desc\n");
        graphics_write_textr("ERROR: Can't read root folder!\n");
        free_mem(root_desc);
        return;
    }

    serial_write_str("Root folder has ");
    serial_write_dec(root_desc->entry_count);
    serial_write_str(" entries\n");

    for (uint32_t i = 0; i < root_desc->entry_count; i++) {
        serial_write_str("  Entry ");
        serial_write_dec(i);
        serial_write_str(": ");
        serial_write_str(root_desc->entries[i].name);
        serial_write_str(" (block ");
        serial_write_dec(root_desc->entries[i].block_offset);
        serial_write_str(")\n");
    }

    free_mem(root_desc);
    graphics_write_textr("Format complete!\n");
    serial_write_str("=== FORMAT DEBUG DONE ===\n\n");
}

// ===========================================
// LISTROOT COMMAND
// ===========================================

void cmd_listroot_debug(int argc, const char** argv) {
    serial_write_str("\n=== LISTROOT DEBUG ===\n");
    
    minimafs_drive_t* drive = get_drive(0);
    if (!drive) {
        serial_write_str("ERROR: get_drive(0) = NULL\n");
        graphics_write_textr("ERROR: Drive 0 not found!\n");
        return;
    }
    
    if (!drive->mounted) {
        serial_write_str("ERROR: Drive 0 not mounted\n");
        graphics_write_textr("ERROR: Drive 0 not mounted! Use 'format' first.\n");
        return;
    }
    
    serial_write_str("Drive 0 is mounted. Root block=");
    serial_write_dec(drive->storage_desc.root_block);
    serial_write_str("\n");
    
    // Heap-allocate - folder_desc_t is ~6KB, unsafe on kernel stack
    minimafs_folder_desc_t* root_desc = (minimafs_folder_desc_t*)alloc(sizeof(minimafs_folder_desc_t));
    if (!root_desc) {
        serial_write_str("ERROR: OOM\n");
        return;
    }

    if (!minimafs_read_folder_desc(drive, "/", root_desc)) {
        serial_write_str("ERROR: Failed to read root folder.desc\n");
        graphics_write_textr("ERROR: Can't read root folder descriptor!\n");
        free_mem(root_desc);
        return;
    }
    
    serial_write_str("Root folder.desc loaded:\n");
    serial_write_str("  Path: ");
    serial_write_str(root_desc->path);
    serial_write_str("\n  Block: ");
    serial_write_dec(root_desc->block_offset);
    serial_write_str("\n  Entry count: ");
    serial_write_dec(root_desc->entry_count);
    serial_write_str("\n");
    
    if (root_desc->entry_count == 0) {
        serial_write_str("Root folder is empty!\n");
        graphics_write_textr("Root directory is empty.\n");
        free_mem(root_desc);
        return;
    }
    
    serial_write_str("All entries (including hidden):\n");
    for (uint32_t i = 0; i < root_desc->entry_count; i++) {
        serial_write_str("  [");
        serial_write_dec(i);
        serial_write_str("] ");
        serial_write_str(root_desc->entries[i].name);
        serial_write_str(" - Block ");
        serial_write_dec(root_desc->entries[i].block_offset);
        serial_write_str(", Type=");
        serial_write_dec(root_desc->entries[i].type);
        serial_write_str(", Hidden=");
        serial_write_dec(root_desc->entries[i].hidden ? 1 : 0);
        serial_write_str("\n");
    }

    free_mem(root_desc);

    // Heap-allocate entries buffer - 64 * ~77 bytes = ~5KB, too large for stack
    minimafs_dir_entry_t* entries = (minimafs_dir_entry_t*)alloc(
        MINIMAFS_MAX_ROOT_ENTRIES * sizeof(minimafs_dir_entry_t));
    if (!entries) {
        serial_write_str("ERROR: OOM for entries\n");
        return;
    }

    uint32_t count = minimafs_list_dir("0:/", entries, MINIMAFS_MAX_ROOT_ENTRIES);
    
    serial_write_str("minimafs_list_dir returned ");
    serial_write_dec(count);
    serial_write_str(" entries\n");
    
    graphics_write_textr("Root directory contents:\n");
    if (count == 0) {
        graphics_write_textr("  (empty)\n");
    } else {
        for (uint32_t i = 0; i < count; i++) {
            graphics_write_textr("  ");
            graphics_write_textr(entries[i].name);
            if (entries[i].type == MINIMAFS_TYPE_DIR) {
                graphics_write_textr(" [DIR]");
            }
            graphics_write_textr("\n");
        }
    }

    free_mem(entries);
    serial_write_str("=== LISTROOT DEBUG DONE ===\n\n");
}

// ===========================================
// RECURSIVE LISTDISK COMMAND
// ===========================================

// Helper: print a single folder level, then recurse into subdirs
// We copy subdir names before freeing folder, then recurse after
void listdisk_recursive(const char* path, int indent) {
    minimafs_drive_t* drive = get_drive(0);
    if (!drive || !drive->mounted) return;

    // Heap-allocate: this is recursive so each level would add ~6KB to stack
    minimafs_folder_desc_t* folder = (minimafs_folder_desc_t*)alloc(sizeof(minimafs_folder_desc_t));
    if (!folder) return;

    if (!minimafs_read_folder_desc(drive, path, folder)) {
        free_mem(folder);
        return;
    }

    for (int i = 0; i < indent; i++) graphics_write_textr("  ");
    graphics_write_textr(path);
    graphics_write_textr("/\n");

    // Collect subdir names before freeing folder
    uint32_t entry_count = folder->entry_count;

    // Print all entries and collect subdir paths
    // We process files first, then recurse into dirs after freeing folder
    char subdirs[MINIMAFS_MAX_ROOT_ENTRIES][MINIMAFS_MAX_PATH];
    uint32_t subdir_count = 0;

    for (uint32_t i = 0; i < entry_count; i++) {
        minimafs_dir_entry_t* entry = &folder->entries[i];

        for (int j = 0; j < indent + 1; j++) graphics_write_textr("  ");
        graphics_write_textr(entry->name);

        if (entry->type == MINIMAFS_TYPE_DIR) {
            graphics_write_textr(" [DIR]\n");
            if (subdir_count < MINIMAFS_MAX_ROOT_ENTRIES) {
                if (strcmp(path, "/") == 0) {
                    snprintf(subdirs[subdir_count], MINIMAFS_MAX_PATH, "/%s", entry->name);
                } else {
                    snprintf(subdirs[subdir_count], MINIMAFS_MAX_PATH, "%s/%s", path, entry->name);
                }
                subdir_count++;
            }
        } else {
            graphics_write_textr("\n");
        }
    }

    free_mem(folder);

    // Now recurse into subdirs with folder freed
    for (uint32_t i = 0; i < subdir_count; i++) {
        listdisk_recursive(subdirs[i], indent + 1);
    }
}

void cmd_listdisk(int argc, const char** argv) {
    serial_write_str("\n=== LISTDISK ===\n");

    minimafs_drive_t* drive = get_drive(0);
    if (!drive || !drive->mounted) {
        serial_write_str("ERROR: Drive 0 not mounted!\n");
        graphics_write_textr("Drive not mounted!\n");
        return;
    }

    listdisk_recursive("/", 0);

    serial_write_str("=== LISTDISK DONE ===\n\n");
    graphics_write_textr("Disk listing complete.\n");
}

static uint8_t parse_u8(const char* s, uint8_t def) {
    if (!s || !*s) return def;
    uint32_t val = 0;
    while (*s >= '0' && *s <= '9') {
        val = (val * 10) + (uint32_t)(*s - '0');
        s++;
    }
    if (val > 255) val = 255;
    return (uint8_t)val;
}

void cmd_mount(int argc, const char** argv) {
    minimafs_disk_device_t* device;
    device = getminimadrive();
    uint8_t drive = 1;
    if (argc >= 2) {
        drive = parse_u8(argv[1], 1);
    }
    int success = mountdrive(device, drive);
    if (success == 1) {
        graphics_write_textr("Mount succeded.\n");
    }else if (success == 2) {
        graphics_write_textr("MinimaFS: Drive already mounted\n");
    }else if (success == 3) {
        graphics_write_textr("MinimaFS: Failed to parse storage.desc\n");
    }else if (success == 4) {
        graphics_write_textr("MinimaFS: Invalid root block\n");
    }else if (success == 5) {
        graphics_write_textr("MinimaFS: Drive too large for bitmap\n");
    } else {
        graphics_write_textr("Mount failed.\n");
    }

    serial_write_str("DEBUG: listing drive ");
    serial_write_dec(drive);
    serial_write_str("\n");
    minimafs_drive_t* d = get_drive(drive);

    if (!d) {
        serial_write_str("Drive = NULL\n");
    } else if (!d->mounted) {
        serial_write_str("Drive not mounted\n");
    } else {
        serial_write_str("Drive OK\n");
    }

}

void cmd_initdisk(int argc, const char** argv) {
    uint8_t drive = 0;
    if (argc >= 2) {
        drive = parse_u8(argv[1], 0);
    } else {
        graphics_write_textr("No drive number specified, defaulting to 0.\n");
        drive = 0;
    }
    initializeminimafs(drive);
}

void register_listdisk(void) {
    command_register("listdisk", cmd_listdisk);
}

void register_format_debug(void) {
    command_register("format", cmd_format_debug);
}

void register_listroot_debug(void) {
    command_register("listroot", cmd_listroot_debug);
}

void register_mount(void) {
    command_register("mount", cmd_mount);
}

void register_initdisk(void) {
    command_register("initdisk", cmd_initdisk);
}


// ===========================================
// CREATE MUSIC FILE COMMAND
// Usage: createmusicfile [drive]
// Writes embedded music.o data to <drive>:/music.adi
// ===========================================

static bool write_music_adi(uint8_t drive_number) {
    minimafs_drive_t* d = get_drive(drive_number);
    if (!d || !d->mounted) {
        graphics_write_textr("Invalid or unmounted drive\n");
        return false;
    }

    const uint8_t* data     = _binary_music_wav_start;
    uint32_t       data_len = (uint32_t)(_binary_music_wav_end - _binary_music_wav_start);
    if (data_len == 0) {
        graphics_write_textr("No embedded music data\n");
        return false;
    }
    TRACE_MSG("Creating music file");
    const uint32_t sample_rate    = 48000;
    const uint8_t  channels       = 2;
    const uint8_t  volume         = 80;
    uint32_t       total_samples  = data_len * 2;
    uint32_t       length_seconds = 1;
    if (sample_rate > 0 && channels > 0) {
        uint32_t denom = sample_rate * channels;
        length_seconds = (total_samples + denom - 1) / denom;
    }

    // Build the ADI text header
    char header[256];
    int header_len = snprintf(header, sizeof(header),
        "#Audio data generated by ADI converter\n"
        "AudioFormat=IADPCM\n"
        "AudioLength=%u\n"
        "AudioDatalen=%u\n"
        "Globalvol=%u\n"
        "SampleRate=%u\n"
        "Channels=%u\n"
        "#DATA\n",
        length_seconds, data_len, volume, sample_rate, channels
    );
    if (header_len <= 0 || (size_t)header_len >= sizeof(header)) {
        graphics_write_textr("Failed to build ADI header\n");
        return false;
    }

    char path[32];
    snprintf(path, sizeof(path), "%u:/music.adi", drive_number);

    serial_write_str("createmusicfile: writing ");
    serial_write_dec(data_len);
    serial_write_str(" bytes\n");

    // Write header + raw audio data together in one call.
    // minimafs_write_file_segments handles block allocation and folder registration.
    // seg1 = ADI text header, seg2 = raw PCM/ADPCM data.
    if (!minimafs_write_file_segments(path,
            header,  (uint32_t)header_len,
            data,    data_len,
            "audio", "adi")) {
        graphics_write_textr("Failed to write music.adi\n");
        return false;
    }

    serial_write_str("createmusicfile: write complete\n");
    graphics_write_textr("music.adi written to ");
    graphics_write_textr(path);
    graphics_write_textr("\n");
    return true;
}

void cmd_createmusicfile(int argc, const char** argv) {
    TRACE_ENTER();
    trace_enable(true);
    trace_cli(__FILE__, __func__, __LINE__);
    trace_sti(__FILE__, __func__, __LINE__);
    trace_assert_irq_consistency(__FILE__, __func__, __LINE__);
    uint8_t drive = 0;
    if (argc >= 2) drive = parse_u8(argv[1], 0);
    if (!write_music_adi(drive)) {
        graphics_write_textr("createmusicfile failed\n");
    }
    graphics_write_textr("Done music file created.\n");
    trace_sti(__FILE__, __func__, __LINE__);
    trace_dump_interrupt_audit();
    TRACE_EXIT();
}

void register_createmusicfile(void) {
    command_register("createmusicfile", cmd_createmusicfile);
}

REGISTER_COMMAND(register_createmusicfile);

// ===========================================
// READ COMMAND
// Usage: read <path> [--metadata]
// Reads a file's data and prints it to the terminal.
// With --metadata also prints the file's header fields.
// ===========================================

void cmd_read(int argc, const char** argv) {
    if (argc < 2) {
        graphics_write_textr("Usage: read <path> [--metadata]\n");
        graphics_write_textr("  Example: read 0:/etc/system.conf\n");
        graphics_write_textr("  Example: read 0:/etc/system.conf --metadata\n");
        return;
    }

    const char* path = argv[1];
    bool show_metadata = (argc >= 3 && strcmp(argv[2], "--metadata") == 0);

    serial_write_str("read: opening '");
    serial_write_str(path);
    serial_write_str("'\n");

    minimafs_file_handle_t* f = minimafs_open(path, true);
    if (!f) {
        graphics_write_textr("ERROR: Could not open '");
        graphics_write_textr(path);
        graphics_write_textr("'\n");
        graphics_write_textr("  (File may not exist, or path is a directory)\n");
        serial_write_str("read: minimafs_open returned NULL\n");
        return;
    }

    // ---- Metadata ----
    if (show_metadata) {
        graphics_write_textr("--- Metadata ---\n");

        graphics_write_textr("Name:     ");
        graphics_write_textr(f->metadata.filename[0] ? f->metadata.filename : "(none)");
        graphics_write_textr("\n");

        graphics_write_textr("Type:     ");
        graphics_write_textr(f->metadata.filetype[0] ? f->metadata.filetype : "(none)");
        graphics_write_textr("\n");

        graphics_write_textr("Format:   ");
        graphics_write_textr(f->metadata.fileformat[0] ? f->metadata.fileformat : "(none)");
        graphics_write_textr("\n");

        graphics_write_textr("Parent:   ");
        graphics_write_textr(f->metadata.parent_folder[0] ? f->metadata.parent_folder : "/");
        graphics_write_textr("\n");

        graphics_write_textr("Created:  ");
        graphics_write_textr(f->metadata.created_date[0] ? f->metadata.created_date : "unknown");
        graphics_write_textr("\n");

        graphics_write_textr("Modified: ");
        graphics_write_textr(f->metadata.last_changed[0] ? f->metadata.last_changed : "unknown");
        graphics_write_textr("\n");

        graphics_write_textr("Hidden:   ");
        graphics_write_textr(f->metadata.hidden ? "yes" : "no");
        graphics_write_textr("\n");

        graphics_write_textr("Runnable: ");
        graphics_write_textr(f->metadata.runnable ? "yes" : "no");
        graphics_write_textr("\n");

        // Print sizes without %llu — split into KB + remainder bytes
        uint32_t file_len = f->metadata.file_length;
        uint32_t data_len = f->metadata.data_length;

        graphics_write_textr("File len: ");
        graphics_write_textr_udec(file_len);
        graphics_write_textr(" bytes\n");

        graphics_write_textr("Data len: ");
        graphics_write_textr_udec(data_len);
        graphics_write_textr(" bytes\n");

        graphics_write_textr("Block:    ");
        graphics_write_textr_udec(f->metadata.block_offset);
        graphics_write_textr(" (count: ");
        graphics_write_textr_udec(f->metadata.block_count);
        graphics_write_textr(")\n");

        graphics_write_textr("--- Data ---\n");
    }

    // ---- File data ----
    if (f->data_size == 0) {
        graphics_write_textr("(file has no data content)\n");
        minimafs_close(f);
        return;
    }

    // Read in chunks so we never need a large stack buffer.
    // 256 bytes per chunk keeps stack usage negligible.
    #define READ_CHUNK 256
    uint8_t* chunk = (uint8_t*)alloc_unzeroed(READ_CHUNK + 1);
    if (!chunk) {
        graphics_write_textr("ERROR: OOM reading file\n");
        minimafs_close(f);
        return;
    }

    uint32_t total_read = 0;
    bool last_was_newline = false;

    while (total_read < f->data_size) {
        uint32_t n = minimafs_read(f, chunk, READ_CHUNK);
        if (n == 0) break;

        chunk[n] = '\0';

        // Print byte-by-byte so control characters are handled cleanly.
        // Skip null bytes (padding at end of block).
        for (uint32_t i = 0; i < n; i++) {
            uint8_t c = chunk[i];
            if (c == 0) break;           // end of actual text content
            if (c == '\r') continue;     // strip carriage returns
            last_was_newline = (c == '\n');
            graphics_write_textr_char((char)c);
        }

        total_read += n;
    }

    // Ensure output ends on a fresh line
    if (!last_was_newline) {
        graphics_write_textr("\n");
    }

    free_mem(chunk);
    minimafs_close(f);

    serial_write_str("read: done, ");
    serial_write_dec(total_read);
    serial_write_str(" bytes read\n");
}

void register_read(void) {
    command_register("read", cmd_read);
}

REGISTER_COMMAND(register_initdisk);
REGISTER_COMMAND(register_mount);
REGISTER_COMMAND(register_format_debug);
REGISTER_COMMAND(register_listroot_debug);
REGISTER_COMMAND(register_listdisk);
REGISTER_COMMAND(register_read);
