#include <stdbool.h>
#include "print.h"
#include "graphics.h"
#include "x86_64/commandhandler.h"
#include "x86_64/commandreg.h"
#include "string.h"
#include "minimafshandler.h"
#include "x86_64/minimafs.h"
#include "x86_64/allocator.h"
#include "serial.h"
#include "systeminfo.h"
#include "music.h"
#include "x86_64/exec_trace.h"
#include "x86_64/safeints.h"

// ===========================================
// FORMAT COMMAND
// ===========================================

void cmd_format_debug(int argc, const char** argv) {
    serial_write_str("\n=== FORMAT DEBUG ===\n");
    graphics_write_textr("Formatting drive...\n");

    minimafs_disk_device_t* device = getminimadrive();
    if (!device) {
        graphics_write_textr("ERROR: No device!\n");
        serial_write_str("ERROR: getminimadrive() returned NULL\n");
        return;
    }

    serial_write_str("Device OK\n");
    minimafs_drive_t* existing = get_drive(0);
    if (existing && existing->mounted) {
        serial_write_str("Drive 0 already mounted, unmounting before format...\n");
        minimafs_unmount(0);
    }

    uint64_t size = 128ULL * 1024 * 1024;  // 128 MB

    serial_write_str("Calling minimafs_format...\n");
    if (!minimafs_format(device, size, 0, "maindisk")) {
        graphics_write_textr("ERROR: Formatting failed!\n");
        serial_write_str("ERROR: minimafs_format returned false\n");
        return;
    }

    graphics_write_textr("Format OK. Mounting...\n");
    serial_write_str("Format succeeded. Calling minimafs_mount...\n");

    int mount_result = minimafs_mount(device, 0);
    if (mount_result != 1) {
        graphics_write_textr("ERROR: Mount failed! Code=");
        char buf[16];
        snprintf(buf, sizeof(buf), "%d", mount_result);
        graphics_write_textr(buf);
        graphics_write_textr("\n");
        serial_write_str("ERROR: minimafs_mount returned ");
        serial_write_dec(mount_result);
        serial_write_str("\n");
        return;
    }

    graphics_write_textr("Mounted OK.\n");
    serial_write_str("Mount succeeded.\n");

    minimafs_drive_t* drive = get_drive(0);
    if (!drive || !drive->mounted) {
        serial_write_str("ERROR: Drive 0 not accessible\n");
        graphics_write_textr("ERROR: Drive not accessible!\n");
        return;
    }

    serial_write_str("Drive 0 is mounted. Root block=");
    serial_write_dec(drive->storage_desc.root_block);
    serial_write_str("\n");

    minimafs_refresh_storage_desc(drive);

    serial_write_str("Creating system directory structure...\n");
    graphics_write_textr("Creating 0:/Etc/System.conf...\n");

    minimafs_mkdir("0:/");
    if (!minimafs_mkdir("0:/Etc")) {
        serial_write_str("WARNING: Failed to create 0:/Etc (may already exist)\n");
    }
    minimafs_create_file("0:/Etc/System.conf", "text", "conf");

    // Build System.conf content — SYSTEMVER is a string from systeminfo.h
    char date_str[32];
    minimafs_get_datetime(date_str, sizeof(date_str));

    char* conf_content = (char*)alloc(512);
    if (!conf_content) {
        serial_write_str("ERROR: OOM for conf_content\n");
        return;
    }

    char* p = conf_content;
    p += sprintf(p, "# MinimalOS System Configuration\n");
    p += sprintf(p, "# Auto-generated by format\n");
    p += sprintf(p, "#\n");
    p += sprintf(p, "version=%s\n",     SYSTEMVER);
    p += sprintf(p, "formatted=%s\n",   date_str);
    p += sprintf(p, "hostname=MinimalDevice\n");
    p += sprintf(p, "drive=%u\n",       (unsigned int)drive->drive_number);
    p += sprintf(p, "fs=MinimaFS\n");
    /* Default keyboard layout selector. May be a built-in name (e.g.
     * "US", "SE") or a path to a .kbr file (e.g. "0:/kbr/german.kbr").
     * Change with the 'kbrlayout set <name|path>' terminal command,
     * which keeps this line in sync automatically. */
    p += sprintf(p, "KeyboardLayout=SE\n");

    uint32_t conf_len = (uint32_t)(p - conf_content);

    // Open the file and write the content
    minimafs_file_handle_t* conf_file = minimafs_open("0:/Etc/System.conf", false);
    if (!conf_file) {
        serial_write_str("ERROR: Could not open System.conf for writing\n");
    } else {
        minimafs_write(conf_file, conf_content, conf_len);
        minimafs_close(conf_file);
        serial_write_str("System.conf written (");
        serial_write_dec(conf_len);
        serial_write_str(" bytes)\n");
    }

    free_mem(conf_content);
    graphics_write_textr("File created OK.\n");

    // Verify the file was registered in the Etc folder
    minimafs_folder_desc_t* etc_desc = (minimafs_folder_desc_t*)alloc(sizeof(minimafs_folder_desc_t));
    if (!etc_desc) {
        serial_write_str("ERROR: OOM for etc_desc\n");
        return;
    }

    if (!minimafs_read_folder_desc(drive, "/Etc", etc_desc)) {
        serial_write_str("ERROR: Failed to read Etc folder.desc\n");
        graphics_write_textr("ERROR: Can't read Etc folder!\n");
        free_mem(etc_desc);
        return;
    }

    serial_write_str("Etc folder has ");
    serial_write_dec(etc_desc->entry_count);
    serial_write_str(" entries\n");

    for (uint32_t i = 0; i < etc_desc->entry_count; i++) {
        serial_write_str("  Entry ");
        serial_write_dec(i);
        serial_write_str(": ");
        serial_write_str(etc_desc->entries[i].name);
        serial_write_str(" (block ");
        serial_write_dec(etc_desc->entries[i].block_offset);
        serial_write_str(")\n");
    }

    free_mem(etc_desc);
    graphics_write_textr("Format complete!\n");
    serial_write_str("=== FORMAT DEBUG DONE ===\n\n");
}

// ===========================================
// LISTROOT COMMAND
// ===========================================

void cmd_listroot_debug(int argc, const char** argv) {
    serial_write_str("\n=== LISTROOT DEBUG ===\n");
    
    minimafs_drive_t* drive = get_drive(0);
    if (!drive) {
        serial_write_str("ERROR: get_drive(0) = NULL\n");
        graphics_write_textr("ERROR: Drive 0 not found!\n");
        return;
    }
    
    if (!drive->mounted) {
        serial_write_str("ERROR: Drive 0 not mounted\n");
        graphics_write_textr("ERROR: Drive 0 not mounted! Use 'format' first.\n");
        return;
    }
    
    serial_write_str("Drive 0 is mounted. Root block=");
    serial_write_dec(drive->storage_desc.root_block);
    serial_write_str("\n");
    
    // Heap-allocate - folder_desc_t is ~6KB, unsafe on kernel stack
    minimafs_folder_desc_t* root_desc = (minimafs_folder_desc_t*)alloc(sizeof(minimafs_folder_desc_t));
    if (!root_desc) {
        serial_write_str("ERROR: OOM\n");
        return;
    }

    if (!minimafs_read_folder_desc(drive, "/", root_desc)) {
        serial_write_str("ERROR: Failed to read root folder.desc\n");
        graphics_write_textr("ERROR: Can't read root folder descriptor!\n");
        free_mem(root_desc);
        return;
    }
    
    serial_write_str("Root folder.desc loaded:\n");
    serial_write_str("  Path: ");
    serial_write_str(root_desc->path);
    serial_write_str("\n  Block: ");
    serial_write_dec(root_desc->block_offset);
    serial_write_str("\n  Entry count: ");
    serial_write_dec(root_desc->entry_count);
    serial_write_str("\n");
    
    if (root_desc->entry_count == 0) {
        serial_write_str("Root folder is empty!\n");
        graphics_write_textr("Root directory is empty.\n");
        free_mem(root_desc);
        return;
    }
    
    serial_write_str("All entries (including hidden):\n");
    for (uint32_t i = 0; i < root_desc->entry_count; i++) {
        serial_write_str("  [");
        serial_write_dec(i);
        serial_write_str("] ");
        serial_write_str(root_desc->entries[i].name);
        serial_write_str(" - Block ");
        serial_write_dec(root_desc->entries[i].block_offset);
        serial_write_str(", Type=");
        serial_write_dec(root_desc->entries[i].type);
        serial_write_str(", Hidden=");
        serial_write_dec(root_desc->entries[i].hidden ? 1 : 0);
        serial_write_str("\n");
    }

    free_mem(root_desc);

    // Heap-allocate entries buffer - 64 * ~77 bytes = ~5KB, too large for stack
    minimafs_dir_entry_t* entries = (minimafs_dir_entry_t*)alloc(
        MINIMAFS_MAX_ROOT_ENTRIES * sizeof(minimafs_dir_entry_t));
    if (!entries) {
        serial_write_str("ERROR: OOM for entries\n");
        return;
    }

    uint32_t count = minimafs_list_dir("0:/", entries, MINIMAFS_MAX_ROOT_ENTRIES);
    
    serial_write_str("minimafs_list_dir returned ");
    serial_write_dec(count);
    serial_write_str(" entries\n");
    
    graphics_write_textr("Root directory contents:\n");
    if (count == 0) {
        graphics_write_textr("  (empty)\n");
    } else {
        for (uint32_t i = 0; i < count; i++) {
            graphics_write_textr("  ");
            graphics_write_textr(entries[i].name);
            if (entries[i].type == MINIMAFS_TYPE_DIR) {
                graphics_write_textr(" [DIR]");
            }
            graphics_write_textr("\n");
        }
    }

    free_mem(entries);
    serial_write_str("=== LISTROOT DEBUG DONE ===\n\n");
}

// ===========================================
// RECURSIVE list COMMAND
// ===========================================

// Helper: print a single folder level, then recurse into subdirs
// We copy subdir names before freeing folder, then recurse after
static char g_current_directory[MINIMAFS_MAX_PATH] = "0:/";
static char g_resolved_path[MINIMAFS_MAX_PATH];
static char g_list_local_path[MINIMAFS_MAX_PATH];
static bool fs_resolve_path(const char* input, char* resolved);

const char* fs_get_current_directory(void) {
    return g_current_directory;
}

void list_recursive(uint8_t drive_number, const char* path, int indent) {
    minimafs_drive_t* drive = get_drive(drive_number);
    if (!drive || !drive->mounted) return;

    // Heap-allocate: this is recursive so each level would add ~6KB to stack
    minimafs_folder_desc_t* folder = (minimafs_folder_desc_t*)alloc(sizeof(minimafs_folder_desc_t));
    if (!folder) return;

    if (!minimafs_read_folder_desc(drive, path, folder)) {
        free_mem(folder);
        return;
    }

    for (int i = 0; i < indent; i++) graphics_write_textr("  ");
    graphics_write_textr(path);
    graphics_write_textr("/\n");

    uint32_t entry_count = folder->entry_count;

    // HEAP — 64 * 1024 bytes is 16x the 4KB kernel stack; never on-stack,
    // especially in a recursive function.
    char (*subdirs)[MINIMAFS_MAX_PATH] =
    (char (*)[MINIMAFS_MAX_PATH])alloc(MINIMAFS_MAX_ROOT_ENTRIES * MINIMAFS_MAX_PATH);
    uint32_t subdir_count = 0;

    if (!subdirs) {
        serial_write_str("list_recursive: OOM allocating subdirs buffer\n");
        free_mem(folder);
        return;
    }

    for (uint32_t i = 0; i < entry_count; i++) {
        minimafs_dir_entry_t* entry = &folder->entries[i];

        for (int j = 0; j < indent + 1; j++) graphics_write_textr("  ");
        graphics_write_textr(entry->name);

        if (entry->type == MINIMAFS_TYPE_DIR) {
            graphics_write_textr(" [DIR]\n");
            if (subdir_count < MINIMAFS_MAX_ROOT_ENTRIES) {
                if (strcmp(path, "/") == 0) {
                    snprintf(subdirs[subdir_count], MINIMAFS_MAX_PATH, "/%s", entry->name);
                } else {
                    snprintf(subdirs[subdir_count], MINIMAFS_MAX_PATH, "%s/%s", path, entry->name);
                }
                subdir_count++;
            }
        } else {
            graphics_write_textr("\n");
        }
    }

    free_mem(folder);

    // Recurse into subdirs with folder already freed
    for (uint32_t i = 0; i < subdir_count; i++) {
        list_recursive(drive_number, subdirs[i], indent + 1);
    }

    free_mem(subdirs);
}

void cmd_list(int argc, const char** argv) {
    serial_write_str("\n=== list ===\n");

    const char* requested_path = "";
    bool recursive = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--recursive") == 0 ||
            strcmp(argv[i], "--recurvesive") == 0) {
            recursive = true;
        } else if (*requested_path == '\0') {
            requested_path = argv[i];
        }
    }
    if (!fs_resolve_path(requested_path, g_resolved_path)) {
        graphics_write_textr("list: invalid path\n");
        return;
    }

    uint8_t drive_number;
    if (!minimafs_parse_path(g_resolved_path, &drive_number, g_list_local_path)) {
        graphics_write_textr("list: invalid path\n");
        return;
    }

    minimafs_drive_t* drive = get_drive(drive_number);
    if (!drive || !drive->mounted) {
        serial_write_str("ERROR: Drive not mounted!\n");
        graphics_write_textr("Drive not mounted!\n");
        return;
    }

    if (!minimafs_is_dir(g_resolved_path)) {
        graphics_write_textr("list: not a directory\n");
        return;
    }

    if (recursive) {
        list_recursive(drive_number, g_list_local_path, 0);
        serial_write_str("=== list DONE ===\n\n");
        return;
    }

    minimafs_dir_entry_t* entries = (minimafs_dir_entry_t*)alloc(
        MINIMAFS_MAX_ROOT_ENTRIES * sizeof(minimafs_dir_entry_t));
    if (!entries) {
        graphics_write_textr("list: out of memory\n");
        return;
    }

    uint32_t count = minimafs_list_dir(g_resolved_path, entries,
                                       MINIMAFS_MAX_ROOT_ENTRIES);
    for (uint32_t i = 0; i < count; i++) {
        graphics_write_textr(entries[i].name);
        if (entries[i].type == MINIMAFS_TYPE_DIR)
            graphics_write_textr(" [DIR]");
        graphics_write_textr("\n");
    }
    free_mem(entries);

    serial_write_str("=== list DONE ===\n\n");
}

static uint8_t parse_u8(const char* s, uint8_t def) {
    if (!s || !*s) return def;
    uint32_t val = 0;
    while (*s >= '0' && *s <= '9') {
        val = (val * 10) + (uint32_t)(*s - '0');
        s++;
    }
    if (val > 255) val = 255;
    return (uint8_t)val;
}

static bool fs_append_segment(char* path, size_t* length, const char* segment) {
    size_t segment_length = strlen(segment);
    if (*length + segment_length + 2 >= MINIMAFS_MAX_PATH) return false;
    if (*length > 1) path[(*length)++] = '/';
    memcpy(path + *length, segment, segment_length);
    *length += segment_length;
    path[*length] = '\0';
    return true;
}

static void fs_remove_last_segment(char* path, size_t* length) {
    if (*length <= 1) {
        *length = 1;
        path[1] = '\0';
        return;
    }
    while (*length > 1 && path[*length - 1] != '/') (*length)--;
    if (*length > 1) (*length)--;
    path[*length] = '\0';
}

static bool fs_resolve_path(const char* input, char* resolved) {
    if (!input || !resolved) return false;

    static char base_local[MINIMAFS_MAX_PATH];
    static char input_local[MINIMAFS_MAX_PATH];
    static char combined[MINIMAFS_MAX_PATH * 2];
    static char normalized[MINIMAFS_MAX_PATH];
    static char segment[MINIMAFS_MAX_FILENAME];
    uint8_t drive_number = 0;

    const char* effective_input = *input ? input : g_current_directory;

    if (strchr(effective_input, ':')) {
        if (!minimafs_parse_path(effective_input, &drive_number, input_local)) return false;
        combined[0] = '\0';
        strncpy(combined, input_local, sizeof(combined) - 1);
    } else {
        if (!minimafs_parse_path(g_current_directory, &drive_number, base_local)) return false;
        if (effective_input[0] == '/') {
            snprintf(combined, sizeof(combined), "%s", effective_input);
        } else {
            snprintf(combined, sizeof(combined), "%s/%s", base_local, effective_input);
        }
    }

    normalized[0] = '/';
    normalized[1] = '\0';
    size_t normalized_length = 1;
    char* cursor = combined;
    while (*cursor == '/') cursor++;

    while (*cursor) {
        size_t segment_length = 0;
        while (*cursor && *cursor != '/') {
            if (segment_length + 1 >= sizeof(segment)) return false;
            segment[segment_length++] = *cursor++;
        }
        segment[segment_length] = '\0';
        while (*cursor == '/') cursor++;

        if (segment_length == 0 || strcmp(segment, ".") == 0) continue;
        if (strcmp(segment, "..") == 0) {
            fs_remove_last_segment(normalized, &normalized_length);
        } else if (!fs_append_segment(normalized, &normalized_length, segment)) {
            return false;
        }
    }

    snprintf(resolved, MINIMAFS_MAX_PATH, "%u:%s", drive_number, normalized);
    return true;
}

static bool fs_set_directory_hidden(const char* path, bool hidden) {
    static char local_path[MINIMAFS_MAX_PATH];
    static char parent[MINIMAFS_MAX_PATH];
    static char dirname[MINIMAFS_MAX_FILENAME];
    uint8_t drive_number;

    if (!minimafs_parse_path(path, &drive_number, local_path)) return false;
    minimafs_drive_t* drive = get_drive(drive_number);
    if (!drive) return false;

    const char* slash = strrchr(local_path, '/');
    if (!slash) {
        parent[0] = '\0';
        strncpy(dirname, local_path, sizeof(dirname) - 1);
    } else {
        size_t parent_length = (size_t)(slash - local_path);
        if (parent_length >= sizeof(parent)) return false;
        memcpy(parent, local_path, parent_length);
        parent[parent_length] = '\0';
        strncpy(dirname, slash + 1, sizeof(dirname) - 1);
    }
    dirname[sizeof(dirname) - 1] = '\0';

    minimafs_folder_desc_t* descriptor =
        (minimafs_folder_desc_t*)alloc(sizeof(minimafs_folder_desc_t));
    if (!descriptor || !minimafs_read_folder_desc(drive, parent, descriptor)) {
        if (descriptor) free_mem(descriptor);
        return false;
    }

    bool found = false;
    for (uint32_t i = 0; i < descriptor->entry_count; i++) {
        if (strcmp(descriptor->entries[i].name, dirname) == 0 &&
            descriptor->entries[i].type == MINIMAFS_TYPE_DIR) {
            descriptor->entries[i].hidden = hidden;
            found = true;
            break;
        }
    }

    bool result = found && minimafs_write_folder_desc(drive, descriptor);
    free_mem(descriptor);
    return result;
}

void cmd_cd(int argc, const char** argv) {
    if (argc < 2) {
        graphics_write_textr(g_current_directory);
        graphics_write_textr("\n");
        return;
    }

    if (!fs_resolve_path(argv[1], g_resolved_path) || !minimafs_is_dir(g_resolved_path)) {
        graphics_write_textr("cd: directory not found: ");
        graphics_write_textr(argv[1]);
        graphics_write_textr("\n");
        return;
    }

    strncpy(g_current_directory, g_resolved_path, sizeof(g_current_directory) - 1);
    g_current_directory[sizeof(g_current_directory) - 1] = '\0';
    graphics_write_textr(g_current_directory);
    graphics_write_textr("\n");
}

void cmd_mdr(int argc, const char** argv) {
    if (argc < 2) {
        graphics_write_textr("Usage: mdr <directory> [--hidden]\n");
        return;
    }

    bool hidden = false;
    for (int i = 2; i < argc; i++) {
        if (strcmp(argv[i], "--hidden") == 0) hidden = true;
    }

    if (!fs_resolve_path(argv[1], g_resolved_path) || !minimafs_mkdir(g_resolved_path)) {
        graphics_write_textr("mdr: could not create directory\n");
        return;
    }
    if (hidden && !fs_set_directory_hidden(g_resolved_path, true)) {
        graphics_write_textr("mdr: directory created but hidden flag failed\n");
        return;
    }
    graphics_write_textr("Directory created: ");
    graphics_write_textr(g_resolved_path);
    graphics_write_textr("\n");
}

void cmd_insert(int argc, const char** argv) {
    if (argc < 3) {
        graphics_write_textr("Usage: insert <file> \"text\"\n");
        return;
    }

    if (!fs_resolve_path(argv[1], g_resolved_path) || minimafs_is_dir(g_resolved_path)) {
        graphics_write_textr("insert: invalid file path\n");
        return;
    }

    minimafs_file_handle_t* existing = minimafs_open(g_resolved_path, true);
    if (existing) {
        minimafs_close(existing);
        if (!minimafs_delete_file(g_resolved_path)) {
            graphics_write_textr("insert: could not replace file\n");
            return;
        }
    }
    if (!minimafs_create_file(g_resolved_path, "text", "txt")) {
        graphics_write_textr("insert: could not create file\n");
        return;
    }

    minimafs_file_handle_t* file = minimafs_open(g_resolved_path, false);
    if (!file || minimafs_write(file, argv[2], (uint32_t)strlen(argv[2])) != strlen(argv[2])) {
        if (file) minimafs_close(file);
        graphics_write_textr("insert: write failed\n");
        return;
    }
    minimafs_close(file);
    graphics_write_textr("Inserted text into ");
    graphics_write_textr(g_resolved_path);
    graphics_write_textr("\n");
}

void register_fs_navigation_commands(void) {
    command_register("cd", cmd_cd);
    command_register("mdr", cmd_mdr);
    command_register("insert", cmd_insert);
}

REGISTER_COMMAND(register_fs_navigation_commands);

void cmd_mount(int argc, const char** argv) {
    minimafs_disk_device_t* device;
    device = getminimadrive();
    uint8_t drive = 1;
    if (argc >= 2) {
        drive = parse_u8(argv[1], 1);
    }
    int success = mountdrive(device, drive);
    if (success == 1) {
        graphics_write_textr("Mount succeded.\n");
    }else if (success == 2) {
        graphics_write_textr("MinimaFS: Drive already mounted\n");
    }else if (success == 3) {
        graphics_write_textr("MinimaFS: Failed to parse storage.desc\n");
    }else if (success == 4) {
        graphics_write_textr("MinimaFS: Invalid root block\n");
    }else if (success == 5) {
        graphics_write_textr("MinimaFS: Drive too large for bitmap\n");
    } else {
        graphics_write_textr("Mount failed.\n");
    }

    serial_write_str("DEBUG: listing drive ");
    serial_write_dec(drive);
    serial_write_str("\n");
    minimafs_drive_t* d = get_drive(drive);

    if (!d) {
        serial_write_str("Drive = NULL\n");
    } else if (!d->mounted) {
        serial_write_str("Drive not mounted\n");
    } else {
        serial_write_str("Drive OK\n");
    }

}

void cmd_initdisk(int argc, const char** argv) {
    uint8_t drive = 0;
    if (argc >= 2) {
        drive = parse_u8(argv[1], 0);
    } else {
        graphics_write_textr("No drive number specified, defaulting to 0.\n");
        drive = 0;
    }
    initializeminimafs(drive);
}

void register_list(void) {
    command_register("list", cmd_list);
    command_register("ls", cmd_list);
}

void register_format_debug(void) {
    command_register("format", cmd_format_debug);
}

void register_listroot_debug(void) {
    command_register("listroot", cmd_listroot_debug);
    command_register("lsroot", cmd_listroot_debug);
}

void register_mount(void) {
    command_register("mount", cmd_mount);
}

void register_initdisk(void) {
    command_register("initdisk", cmd_initdisk);
}


// ===========================================
// CREATE MUSIC FILE COMMAND
// Usage: createmusicfile [drive]
// Writes embedded music.o data to <drive>:/music.adi
// ===========================================

static bool write_music_adi(uint8_t drive_number) {
    minimafs_drive_t* d = get_drive(drive_number);
    if (!d || !d->mounted) {
        graphics_write_textr("Invalid or unmounted drive\n");
        return false;
    }

    const uint8_t* data     = _binary_music_wav_start;
    uint32_t       data_len = (uint32_t)(_binary_music_wav_end - _binary_music_wav_start);
    if (data_len == 0) {
        graphics_write_textr("No embedded music data\n");
        return false;
    }

    const uint32_t sample_rate    = 48000;
    const uint8_t  channels       = 2;
    const uint8_t  volume         = 80;

    // IMA-ADPCM: 2 compressed bytes -> 4 stereo samples (L+R+L+R)
    // So total PCM samples = data_len * 2
    // Length in seconds = (data_len * 2) / (sample_rate * channels)
    uint32_t length_seconds = (data_len * 2) / (sample_rate * channels);
    if (length_seconds == 0) length_seconds = 1;

    char path[32];
    snprintf(path, sizeof(path), "%u:/music.adi", drive_number);

    char header[256];
    int header_len = snprintf(header, sizeof(header),
        "#Audio data generated by ADI converter\n"
        "AudioFormat=IADPCM\n"
        "AudioLength=%u\n"
        "AudioDatalen=%u\n"
        "Globalvol=%u\n"
        "SampleRate=%u\n"
        "Channels=%u\n"
        "#DATA\n",
        length_seconds, data_len, volume, sample_rate, channels
    );
    if (header_len <= 0 || (size_t)header_len >= sizeof(header)) {
        graphics_write_textr("Failed to build ADI header\n");
        return false;
    }

    serial_write_str("createmusicfile: writing ");
    serial_write_dec(data_len);
    serial_write_str(" bytes to ");
    serial_write_str(path);
    serial_write_str("\n");

    if (!minimafs_write_file_segments(path,
            header,  (uint32_t)header_len,
            data,    data_len,
            "audio", "adi")) {
        graphics_write_textr("Failed to write music.adi\n");
        return false;
    }

    serial_write_str("createmusicfile: write complete\n");
    graphics_write_textr("music.adi written to ");
    graphics_write_textr(path);
    graphics_write_textr("\n");
    return true;
}

void cmd_createmusicfile(int argc, const char** argv) {
    TRACE_ENTER();
    uint8_t drive = 0;
    if (argc >= 2) drive = parse_u8(argv[1], 0);
    if (!write_music_adi(drive)) {
        graphics_write_textr("createmusicfile failed\n");
    } else {
        graphics_write_textr("Done music file created.\n");
    }
    TRACE_EXIT();
}

void register_createmusicfile(void) {
    command_register("importmusic", cmd_createmusicfile);
}

REGISTER_COMMAND(register_createmusicfile);

// ===========================================
// READ COMMAND
// Usage: read <path> [--metadata]
// Reads a file's data and prints it to the terminal.
// With --metadata also prints the file's header fields.
// ===========================================

void cmd_read(int argc, const char** argv) {
    if (argc < 2) {
        graphics_write_textr("Usage: read <path> [--metadata]\n");
        graphics_write_textr("  Example: read 0:/etc/system.conf\n");
        graphics_write_textr("  Example: read 0:/etc/system.conf --metadata\n");
        return;
    }

    if (!fs_resolve_path(argv[1], g_resolved_path) ||
        minimafs_is_dir(g_resolved_path)) {
        graphics_write_textr("read: path is not a file\n");
        return;
    }

    const char* path = g_resolved_path;
    bool show_metadata = (argc >= 3 && strcmp(argv[2], "--metadata") == 0);

    serial_write_str("read: opening '");
    serial_write_str(path);
    serial_write_str("'\n");

    minimafs_file_handle_t* f = minimafs_open(path, true);
    if (!f) {
        graphics_write_textr("ERROR: Could not open '");
        graphics_write_textr(path);
        graphics_write_textr("'\n");
        graphics_write_textr("  (File may not exist, or path is a directory)\n");
        serial_write_str("read: minimafs_open returned NULL\n");
        return;
    }

    // ---- Metadata ----
    if (show_metadata) {
        graphics_write_textr("--- Metadata ---\n");

        graphics_write_textr("Name:     ");
        graphics_write_textr(f->metadata.filename[0] ? f->metadata.filename : "(none)");
        graphics_write_textr("\n");

        graphics_write_textr("Type:     ");
        graphics_write_textr(f->metadata.filetype[0] ? f->metadata.filetype : "(none)");
        graphics_write_textr("\n");

        graphics_write_textr("Format:   ");
        graphics_write_textr(f->metadata.fileformat[0] ? f->metadata.fileformat : "(none)");
        graphics_write_textr("\n");

        graphics_write_textr("Parent:   ");
        graphics_write_textr(f->metadata.parent_folder[0] ? f->metadata.parent_folder : "/");
        graphics_write_textr("\n");

        graphics_write_textr("Created:  ");
        graphics_write_textr(f->metadata.created_date[0] ? f->metadata.created_date : "unknown");
        graphics_write_textr("\n");

        graphics_write_textr("Modified: ");
        graphics_write_textr(f->metadata.last_changed[0] ? f->metadata.last_changed : "unknown");
        graphics_write_textr("\n");

        graphics_write_textr("Hidden:   ");
        graphics_write_textr(f->metadata.hidden ? "yes" : "no");
        graphics_write_textr("\n");

        graphics_write_textr("Runnable: ");
        graphics_write_textr(f->metadata.runnable ? "yes" : "no");
        graphics_write_textr("\n");

        // Print sizes without %llu — split into KB + remainder bytes
        uint32_t file_len = f->metadata.file_length;
        uint32_t data_len = f->metadata.data_length;

        graphics_write_textr("File len: ");
        graphics_write_textr_udec(file_len);
        graphics_write_textr(" bytes\n");

        graphics_write_textr("Data len: ");
        graphics_write_textr_udec(data_len);
        graphics_write_textr(" bytes\n");

        graphics_write_textr("Block:    ");
        graphics_write_textr_udec(f->metadata.block_offset);
        graphics_write_textr(" (count: ");
        graphics_write_textr_udec(f->metadata.block_count);
        graphics_write_textr(")\n");

        graphics_write_textr("--- Data ---\n");
    }

    // ---- File data ----
    if (f->data_size == 0) {
        graphics_write_textr("(file has no data content)\n");
        minimafs_close(f);
        return;
    }

    // Read in chunks so we never need a large stack buffer.
    // 256 bytes per chunk keeps stack usage negligible.
    #define READ_CHUNK 256
    uint8_t* chunk = (uint8_t*)alloc_unzeroed(READ_CHUNK + 1);
    if (!chunk) {
        graphics_write_textr("ERROR: OOM reading file\n");
        minimafs_close(f);
        return;
    }

    uint32_t total_read = 0;
    bool last_was_newline = false;

    while (total_read < f->data_size) {
        uint32_t n = minimafs_read(f, chunk, READ_CHUNK);
        if (n == 0) break;

        chunk[n] = '\0';

        // Print byte-by-byte so control characters are handled cleanly.
        // Skip null bytes (padding at end of block).
        for (uint32_t i = 0; i < n; i++) {
            uint8_t c = chunk[i];
            if (c == 0) break;           // end of actual text content
            if (c == '\r') continue;     // strip carriage returns
            last_was_newline = (c == '\n');
            graphics_write_textr_char((char)c);
        }

        total_read += n;
    }

    // Ensure output ends on a fresh line
    if (!last_was_newline) {
        graphics_write_textr("\n");
    }

    free_mem(chunk);
    minimafs_close(f);

    serial_write_str("read: done, ");
    serial_write_dec(total_read);
    serial_write_str(" bytes read\n");
}

void register_read(void) {
    command_register("read", cmd_read);
    command_register("rd", cmd_read);
}

REGISTER_COMMAND(register_initdisk);
REGISTER_COMMAND(register_mount);
REGISTER_COMMAND(register_format_debug);
REGISTER_COMMAND(register_listroot_debug);
REGISTER_COMMAND(register_list);
REGISTER_COMMAND(register_read);
